spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: PostgreSQLDialect
      format_sql: true
server:
  error:
    include-message: always
